### PR TITLE
Feature/dashboard

### PR DESCRIPTION
**Pull request by devBuggs**
analytics view updated

### CODE REVIEW

**Comment by devBuggs** [comment]
@bhagwanzestgeek please check and verify

**Review by bhagwanzestgeek — COMMENTED** [review]
review done.

**Review by bhagwanzestgeek — COMMENTED** [review]
all check pass

**Review by bhagwanzestgeek — APPROVED** [review]

**Comment by bhagwanzestgeek** [comment]
@devBuggs ready to merge with develop branch

**Comment by devBuggs** [comment]
done

**Pull request merged**
